#==============================================#
# Xen Crystal by RedSMURF: Configuration file #
#==============================================#

# To add a new light, follow the example below
# [Light Name]
# CRYSTAL_FLAGS                    = a - Solid            b - Reverse     c - Color Random
# CRYSTAL_TEAM                     = 0 - None             1 - Terrorist           2 - Counter-Terrorist   3 - Both
# CRYSTAL_FRAMERATE                = Light's animation speed

# CRYSTAL_TRIGGER_DISTANCE         = Distance in units at which the light can be triggered by players
# CRYSTAL_TRIGGER_DURATION         = Duration in seconds for which the light remains active after being triggered
# CRYSTAL_COLOR_FREQUENCY          = Frequency in seconds at which the light's color changes randomly (only applicable if FLAG_COLOR_RANDOM is set)

# To make an light available in the menu, you must defined at least it's name like this [RedSMURF's Light]
# light model and sound cannot be changed dynamically during gameplay

[Main Settings]
SETTING_DEFAULT_FLAGS               = a
SETTING_DEFAULT_TEAM                = 3
SETTING_DEFAULT_FRAMERATE           = 1.0

SETTING_DEFAULT_TRIGGER_DISTANCE    = 192.0
SETTING_DEFAULT_TRIGGER_DURATION    = 1.0 1.0
SETTING_DEFAULT_COLOR_FREQUENCY     = 1.0 1.0

SETTING_MODEL_CRYSTAL1_NORMAL       = models/XenCrystal/crystal1_normal.mdl
SETTING_MODEL_CRYSTAL2_NORMAL       = models/XenCrystal/crystal2_normal.mdl
SETTING_MODEL_CRYSTAL3_NORMAL       = models/XenCrystal/crystal3_normal.mdl
SETTING_MODEL_CRYSTAL1_LARGE        = models/XenCrystal/crystal1_large.mdl
SETTING_MODEL_CRYSTAL2_LARGE        = models/XenCrystal/crystal2_large.mdl
SETTING_MODEL_CRYSTAL3_LARGE        = models/XenCrystal/crystal3_large.mdl
SETTING_MINS_NORMAL                 = -19.75 -19.70 0.0
SETTING_MAXS_NORMAL                 = 19.75 19.70 48.00
SETTING_MINS_LARGE                  = -29.625 -29.55 0.0
SETTING_MAXS_LARGE                  = 29.625 29.55 72.00

SETTING_CRYSTAL_LOAD                = 1             # Whether to load saved lights data of the current map
SETTING_CRYSTAL_CHECK               = 10.0          # Maximum selection distance when checking nearby lights
SETTING_CRYSTAL_TASK                = 0.1           # Time interval in seconds to check for lights and apply their effects
SETTING_OFFSET_BASE                 = 120.0         # Default forward offset when previewing light placement
SETTING_OFFSET                      = 65.0 900.0    # Default minimum and maximum offset from the player to the light (MIN MAX)
SETTING_OFFSET_STEP                 = 10.0          # Step size when scrolling to move light forward/backward
SETTING_GHOST_ALPHA                 = 120           # Transparency level of the ghost preview model (0 - 255)
SETTING_ROTATION_STEP               = 22.5          # Step size when rotating the light
SETTING_CRYSTAL_LIFE                = 2

[Default]

[T Light]
CRYSTAL_TEAM                  = 1

[CT Light]
CRYSTAL_TEAM                  = 2

[Reverse]
CRYSTAL_FLAGS                 = ab

[Color Changes]
CRYSTAL_FLAGS                 = ac
